use crate::{Forest, Tree, CommitNode, MergeNode};
use std::collections::HashMap;
use termion::color;

/// Generate a structured summary report for the forest.
pub fn generate_summary(forest: &Forest) -> String {
    let mut report = String::new();

    // Header
    report.push_str(&format!(
        "{}╔══════════════════════════════════════╗\r\
",
        color::Fg(color::Green)
    ));
    report.push_str(&format!(
        "║      Git Forest Summary Report       ║\r\
"
    ));
    report.push_str(&format!(
        "╚══════════════════════════════════════╝{}\r\
\r\
",
        color::Fg(color::Reset)
    ));

    // Basic stats
    let total_commits = forest.commit_map.len();
    let total_trees = forest.trees.len();
    let total_merges = forest.merges.len();
    let total_authors = count_authors(forest);

    report.push_str(&format!(
        "{}Commits:{} {}\r\
",
        color::Fg(color::Cyan),
        color::Fg(color::Reset),
        total_commits
    ));
    report.push_str(&format!(
        "{}Trees (branches):{} {}\r\
",
        color::Fg(color::Cyan),
        color::Fg(color::Reset),
        total_trees
    ));
    report.push_str(&format!(
        "{}Merge nodes:{} {}\r\
",
        color::Fg(color::Cyan),
        color::Fg(color::Reset),
        total_merges
    ));
    report.push_str(&format!(
        "{}Unique authors:{} {}\r\
\r\
",
        color::Fg(color::Cyan),
        color::Fg(color::Reset),
        total_authors
    ));

    // Tree details
    report.push_str(&format!(
        "{}Tree Details:{}\r\
",
        color::Fg(color::Yellow),
        color::Fg(color::Reset)
    ));
    report.push_str(&"─".repeat(40));
    report.push_str("\r\
");

    let mut trees_sorted: Vec<&Tree> = forest.trees.values().collect();
    trees_sorted.sort_by(|a, b| b.commits.len().cmp(&a.commits.len()));

    for (i, tree) in trees_sorted.iter().enumerate() {
        let commit_count = tree.commits.len();
        let branch_name = tree.name.as_deref().unwrap_or("(unnamed)");
        let author = tree.author.as_deref().unwrap_or("(unknown)");
        report.push_str(&format!(
            "  {}. {} ({} commits, author: {})\r\
",
            i + 1,
            branch_name,
            commit_count,
            author
        ));
    }

    report.push_str("\r\
");

    // Author breakdown
    report.push_str(&format!(
        "{}Author Breakdown:{}\r\
",
        color::Fg(color::Yellow),
        color::Fg(color::Reset)
    ));
    report.push_str(&"─".repeat(40));
    report.push_str("\r\
");

    let author_counts = count_author_commits(forest);
    let mut authors_sorted: Vec<(&String, &usize)> = author_counts.iter().collect();
    authors_sorted.sort_by(|a, b| b.1.cmp(a.1));

    for (author, count) in &authors_sorted {
        let bar = "█".repeat(*count.min(&40));
        report.push_str(&format!(
            "  {:20} {} {}\r\
",
            author,
            bar,
            count
        ));
    }

    report.push_str("\r\
");

    // Merge storm info
    if !forest.merge_storms.is_empty() {
        report.push_str(&format!(
            "{}Merge Storms:{} {}\r\
",
            color::Fg(color::Red),
            color::Fg(color::Reset),
            forest.merge_storms.len()
        ));
        for (i, storm) in forest.merge_storms.iter().enumerate() {
            report.push_str(&format!(
                "  {}. {} merges at {}\r\
",
                i + 1,
                storm.merge_count,
                storm.location
            ));
        }
        report.push_str("\r\
");
    }

    // Footer
    report.push_str(&format!(
        "{}Generated by git-forest{}\r\
",
        color::Fg(color::Green),
        color::Fg(color::Reset)
    ));

    report
}

/// Count unique authors in the forest.
fn count_authors(forest: &Forest) -> usize {
    let mut authors = std::collections::HashSet::new();
    for commit in forest.commit_map.values() {
        authors.insert(commit.author.clone());
    }
    authors.len()
}

/// Count commits per author.
fn count_author_commits(forest: &Forest) -> HashMap<String, usize> {
    let mut counts = HashMap::new();
    for commit in forest.commit_map.values() {
        *counts.entry(commit.author.clone()).or_insert(0) += 1;
    }
    counts
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Forest, Tree, CommitNode, MergeNode, MergeStorm};

    fn create_test_forest() -> Forest {
        let mut forest = Forest {
            trees: std::collections::HashMap::new(),
            commit_map: std::collections::HashMap::new(),
            merges: Vec::new(),
            merge_storms: Vec::new(),
        };

        // Add a tree
        let mut tree = Tree {
            id: "main".to_string(),
            name: Some("main".to_string()),
            author: Some("Alice".to_string()),
            commits: Vec::new(),
            root: None,
            children: Vec::new(),
            parent: None,
            trunk: Vec::new(),
            branches: Vec::new(),
            color: (100, 200, 50),
            x: 0.0,
            y: 0.0,
            width: 10.0,
            height: 20.0,
        };
        for i in 0..10 {
            let commit_id = format!("abc{}", i);
            let commit = CommitNode {
                id: commit_id.clone(),
                author: "Alice".to_string(),
                message: format!("commit {}", i),
                timestamp: 1000 + i as u64,
                parents: if i == 0 { Vec::new() } else { vec![format!("abc{}", i-1)] },
                children: Vec::new(),
                is_merge: false,
                x: 0.0,
                y: i as f64 * 2.0,
                branch: "main".to_string(),
            };
            tree.commits.push(commit_id.clone());
            forest.commit_map.insert(commit_id, commit);
        }